country list map 구현 완료
dogVelopers/whereWeGoBackOfficeClient pull request #12
Opened 2022-01-01 18:05 UTC by suyeonii99

### Description
list 조회 화면 구현 완료 및 수정, 추가 기능 기초 개발

### Part what want to be especially check
현재 구현한 것 처럼 Main 화면의 국가 조회 컴포넌트의 각 list에 대한 수정을 할 때,
수정 버튼을 클릭한 해당 id를 props로 넘겨받는 방식으로 구현해도 괜찮은지 궁금합니다.. !

2022-01-01 19:29 UTC, hyesungoh requested changes
간단하게 수정 하실 수 있는 것 위주로 코멘트를 달아봤습니다 ! 너무 고생하셨어요 💯 

제가 코멘트단 것을 한 번에 수정하실 필요는 없으시고, `.env` 파일에 대한 것만 수정하신 후 커밋해주시면 다음에 같이 리팩토링을 해봐도 좋을 것 같습니다 👍

2022-01-01 19:29 UTC, hyesungoh commented on .env
> +REACT_APP_API_URL=http://localhost:3004
`.env` 와 같은 환경변수 파일은 깃헙에 안올리는 게 좋을 거 같아요 !

2022-01-01 19:29 UTC, hyesungoh commented on src/styles/GlobalStyle/index.ts
> +* {
해당 부분에서 `모든 요소에 대한 폰트 지정`을 하였으나,

```css
body {
  font-family: 'Noto Sans KR', sans-serif;
}
```

와 같이 body에만 지정을 해두어도 자식 요소에도 적용이 되니 분리를 하는 편이 좋아보입니다 !

---

추가적으로 `Theme` 파일에 fontStyle을 따로 정의해두셨는데 이유가 궁금합니다 !

2022-01-01 19:29 UTC, hyesungoh commented on src/components/CountryList/index.tsx
> +      {data?.map((list) => {
해당 부분에서 `data?.map` 과 같이 옵셔널 체이닝을 적용하는 것 보다는

```tsx
const Component() {
  const {data} = useGetNations();
  
  if (!data) return <div>loading ... </div>
  return (
    <CountryBoxContainer>
      <data.map()> ...
)
}
```

과 같이 로딩에 대한 핸들링을 하는 것이 더 좋지 않을까 생각됩니다 !

로딩 처리에 대해서는 리액트에서 시범적으로 도입하고 있는 [Suspense](https://ko.reactjs.org/docs/concurrent-mode-suspense.html) 에 위임을 할 수 있으니 해당 부분도 한 번 참고하시면 좋을 것 같아용 

> Suspense의 경우 리액트 18버전에서 정식적으로 도입된다고 합니다

---

추가적으로 data에서 map을 돌고 있는 변수명 `list`의 경우 `country` 등 더욱 명시적으로 지을 수 있을 거 같습니다 ! 생각이 어떠신지 말씀해주시면 감사하겠습니다 👍 👍 👍 👍

2022-01-01 19:29 UTC, hyesungoh commented on src/App.tsx
> +  }) => {
해당 Nation에 대한 정보들을 나열한 것을 `INation` 등으로 따로 인터페이스를 빼서 적용하면 코드가 더욱 간결해질 것 같습니다 !

제가 적용한 방법은 WebClient 레포에서 확인하실 수 있습니다 ~! 👍

2022-01-02 23:51 UTC, suyeonii99 commented on .env
> +REACT_APP_API_URL=http://localhost:3004
아 넵! gitIgnore 파일에 올리겠습니당 :)

2022-01-02 23:55 UTC, suyeonii99 commented on src/styles/GlobalStyle/index.ts
> +* {
저번에 알려주신 방식대로 Theme 파일에 지정해 Styled component에 지정하는 방식으로 했는데 GlobalStyle에 위와 같이 지정하는 것이 좋을 것 같군요..!

2022-01-02 23:56 UTC, suyeonii99 commented on src/components/CountryList/index.tsx
> +      {data?.map((list) => {
참고하여 반영하겠습니당 !

2022-01-02 23:57 UTC, suyeonii99 commented on src/App.tsx
> +  }) => {
확인 후 반영하겠습니다 👍🏻

2022-01-05 06:33 UTC, hyesungoh approved these changes

2022-01-05 07:16 UTC, merged